name = "custom bear cub"
license = "MIT"
licenselink = "https://github.com/clente/hugo-bearcub/blob/master/LICENSE"
description = "A lightweight Hugo theme based on Bear Blog and Hugo Bear Blog. It is free, multilingual, optimized for search engines, no-nonsense, responsive, light, and fast. Really fast. Customised with more monochrome theming and the font I like to use."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/VINEGARSYNDROME/customised-hugo-bearcub"

tags = ["blog", "responsive", "minimal", "personal", "dark", "multilingual"]
features = ["favicon", "seo", "no javascript", "rss", "social cards"]

# If the theme has a single author
[author]
    name = "VINEGARSYNDROME"
    homepage = "https://vinegarsyndro.me"

# If porting an existing theme
[original]
    author = "Caio Lente"
    homepage = "https://lente.dev"
    repo = "https://github.com/clente/hugo-bearcub"

# Hugo versions the theme supports
[module]
  [module.hugoVersion]
    min = "0.90"
